# Workshop Web Scraping (Semana 4 - Pandas)

# Pandas DataFrames
DataFrames no Pandas são uma estrutura de dados bidimensional (2-D) definida no pandas que consiste em linhas e colunas.

In [2]:
import pandas as pd

**Criando um DataFrame**

Criação de data frame com os valores das series da oficina passada.

In [3]:
numeric_data = [1, 7, 2] # dado numérico

index = ["x", "y", "z"] # índices pré-definido

data = pd.Series(numeric_data, index)

df = pd.DataFrame(data)

print(df)

   0
x  1
y  7
z  2

Aqui, data pode ser:


1.   Um ou mais dicionários
2.   uma ou mais Series
3.   2D-numpy Ndarray (Array multidimensional)

Lembrando que index por padrão começa por 0: 0, 1, 2 ..., (n-1)

**Criar um DataFrame do Pandas a partir de vários dicionários**

Criando um Dataframe com dois dicionários.

In [4]:
# Definição dicionario 1
dict1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# Definição dicionario 2
dict2 = {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'e': 9}

# Definição de Data com dict1 e dict2
Data = {'primeiro': dict1, 'segundo': dict2}

# Create DataFrame
df = pd.DataFrame(Data)

print(df)

   primeiro  segundo
a       1.0        5
b       2.0        6
c       3.0        7
d       4.0        8
e       NaN        9

**Converter lista de dicionários em um DataFrame do Pandas**

Aqui, pegamos três dicionários e com a ajuda da função from_dict() os convertemos em Pandas DataFrame.

In [6]:
data_c = [
  {'A': 5, 'B': 0, 'C': 3, 'D': 3},
  {'A': 7, 'B': 9, 'C': 3, 'D': 5},
  {'A': 2, 'B': 4, 'C': 7, 'D': 6, 'E': 32}
 ]

df = pd.DataFrame.from_dict(data_c, orient='columns')

print(df)

   A  B  C  D     E
0  5  0  3  3   NaN
1  7  9  3  5   NaN
2  2  4  7  6  32.0

**Criar DataFrame de várias séries**

Criando um dataframe de três séries.

In [7]:
# Definição da series 1
s1 = pd.Series([1, 3, 4, 5, 6, 2, 9])

# Definição da series 2
s2 = pd.Series([1.1, 3.5, 4.7, 5.8, 2.9, 9.3])

# Definição da series 3
s3 = pd.Series(['a', 'b', 'c', 'd', 'e'])

# Definição de Data
Data = {'primeiro':s1, 'segundo':s2, 'terceiro':s3}

# Criar DataFrame
df = pd.DataFrame(Data)

print(df)

   primeiro  segundo terceiro
0         1      1.1        a
1         3      3.5        b
2         4      4.7        c
3         5      5.8        d
4         6      2.9        e
5         2      9.3      NaN
6         9      NaN      NaN

**Converter um array em Pandas Dataframe**

Ao criar um DataFrame de arrays 2D, as dimensões do array 2D devem ser as mesmas.

In [10]:
# Definição de array 2d 1
d1 =[[2, 3, 4], [5, 6, 7], [2,3,5]]

# Definição de array 2d 2
d2 =[[2, 4, 8], [1, 3, 9], [2.23343,'B',0]]

# Definição de Data
Data ={'primeiro': d1, 'segundo': d2}

# Create DataFrame
df_2d = pd.DataFrame(Data)

df_2d

    primeiro          segundo
0  [2, 3, 4]        [2, 4, 8]
1  [5, 6, 7]        [1, 3, 9]
2  [2, 3, 5]  [2.23343, B, 0]

# Acesso e Manipulação dos dados

Lendo dados de um arquivo do tipo .csv

In [25]:
df = pd.read_csv("https://raw.githubusercontent.com/fmassaretto/Workshop-WebScraping/main/arquivos/employees.csv")

# print(type(df))

# print(df)

# df.head(30)
df.tail(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
991,Rose,Female,8/25/2002,5:12 AM,134505.0,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769.0,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450.0,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

**isnull**

Conferindo quais valores sao nulos, retorna true se o valor for nulo e false se tem algum valor na celula

In [ ]:
df.isnull()

**fillna**

Preeenchendo um valor que você definir no lugar dos valores nulos (no caso do pandas, ele substitui nulo (None) por NaN (Not a Number))

In [ ]:

# df["Gender"].fillna("sem valor") # substirui um campo nulo (NaN) de uma coluna específica
df.fillna("nao ok", inplace = True) # substirui um campo nulo (NaN) de todo o dataframe
df.tail(50)

**dropna**

Remove linhas que contenham valor ou valores nulos

In [ ]:
df.dropna() # remove qualquer linha que tenha pelo menos um valor nulo

In [26]:
data = df.dropna(how = 'all') # remove a linha em que todos os valores são nulos
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

**loc e iloc**

loc e iloc são utilizados para fatiar (separar) um conjunto de dados de um dataframe.

Com loc, conseguimos acessar multiplas colunas e fazer alguma logica que só retorne os dados que queremos analisar.

In [ ]:
df.loc[df['Gender'] == 'Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163.0,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [ ]:
df.loc[(df['Gender'] == 'Male') & (df['Salary'] > 100_000.0)].head()

In [ ]:
df.loc[0:10, ['First Name','Salary']]

   First Name    Salary
0     Douglas   97308.0
1      Thomas   61933.0
2       Maria  130590.0
3       Jerry  138705.0
4       Larry  101004.0
5      Dennis  115163.0
6        Ruby   65476.0
7         NaN   45906.0
8      Angela   95570.0
9     Frances  139852.0
10     Louise   63241.0

iloc é baseado na posição onde quero encontrar o dado, ex.:

In [ ]:
df.iloc[0, 4]

97308.0

sendo,

primeiro parametro: linha=0

segundo parametro: coluna=4

Também posso ter uma faixa de dados, ex.:

In [ ]:
df.iloc[0:5, 3:6]

  Last Login Time    Salary  Bonus %
0        12:42 PM   97308.0    6.945
1         6:53 AM   61933.0    4.170
2        11:17 AM  130590.0   11.858
3         1:00 PM  138705.0    9.340
4         4:47 PM  101004.0    1.389

# Exercício

1.   Ler o arquivo csv: https://raw.githubusercontent.com/fmassaretto/Workshop-WebScraping/main/arquivos/TabelaA%C3%A7%C3%B5es.csv
2.   Remover todos os valores nulos
3. Aplicar a seguinte lógica: retornar os dados que o "Val. Min" seja maior que 20.0, o "Val. Max" menor que 50.0 e "Var. Ano (%)" seja positivo